server:
  port: 8080

spring:
  datasource:
    username: root
    password: macongNo.1
    url: jdbc:mysql://140.143.198.105:3306/data-exchange-system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.css.dataexchangesystem.entity

#showSql
logging:
  level:
    com:
      css:
        dataexchangesystem:
        mapping : debug
#swagger
swagger:
  scan: com.css.dataexchangesystem.controller
  title: mxc接口管理工具swagger测试
  description: 用户controller API
  version: 0.0.1

#redis相关配置
redis:
  database: 0
  host: 140.143.198.105
  password: macongNo1
  pool:
    max-active: 200
    max-idle: 10
    max-wait: -1
    min-idle: 0
    max-total: 5
  port: 6379
  timeout: 1000

